version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ccxc/php
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "8001:8001"
      - "4433:4433"
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: example
    volumes:
      - ~/.ccxc/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network


#  mariadb:
#    image: 'bitnami/mariadb:latest'
#    environment:
#      MARIADB_ROOT_PASSWORD: "o04U0d0Jz0R6CI"
#      MARIADB_ROOT_USER: root
#      MARIADB_DATABASE: blog
#      MARIADB_USER: admin
#      MARIADB_PASSWORD: "o04U0d0Jz0R6CI"
#    volumes:
#      - ~/.ccxc/mariadb:/var/lib/mysql
#      - ./mysql/my.cnf:/etc/mysql/my.cnf
#    ports:
#      - "3306:3306"
#    networks:
#      - app-network

  redis:
    image: redis:5.0.7
    volumes:
      - /.ccxc/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
